import type { FieldPolicyRecord, UsageRecord } from './types'

export const initialPolicies: FieldPolicyRecord[] = [
  {
    id: 'policy-customer-service',
    name: 'i18n:pages.dataAccess.mock.policy.customerServiceName',
    endpointCode: 'customer-profile',
    subject: 'i18n:pages.dataAccess.mock.subject.customerServiceRole',
    allowedFields: ['customer_id', 'name', 'level', 'status'],
    deniedFields: ['mobile', 'id_card'],
    status: 'published',
    version: 5,
    updatedAt: 'i18n:pages.dataAccess.mock.time.today1002',
  },
  {
    id: 'policy-order-ops',
    name: 'i18n:pages.dataAccess.mock.policy.orderOperationsName',
    endpointCode: 'order-search',
    subject: 'i18n:pages.dataAccess.mock.subject.orderOperatorRole',
    allowedFields: ['order_id', 'amount', 'status', 'created_at'],
    deniedFields: ['buyer_mobile'],
    status: 'published',
    version: 2,
    updatedAt: 'i18n:pages.dataAccess.mock.time.yesterday1745',
  },
  {
    id: 'policy-partner-app',
    name: 'i18n:pages.dataAccess.mock.policy.partnerApplicationName',
    endpointCode: 'partner-billing',
    subject: 'i18n:pages.dataAccess.mock.subject.partnerApplicationService',
    allowedFields: ['bill_id', 'period', 'amount'],
    deniedFields: ['internal_cost'],
    status: 'draft',
    version: 1,
    updatedAt: 'i18n:pages.dataAccess.mock.time.today0840',
  },
]

export const initialUsageRecords: UsageRecord[] = [
  {
    id: 'usage-20260716-143218',
    userName: 'i18n:pages.dataAccess.mock.user.zhangWei',
    userAccount: 'zhang.wei@example.com',
    targetType: 'endpoint',
    targetName: 'i18n:pages.dataAccess.mock.target.customerProfile',
    targetCode: 'customer-profile',
    usedAt: '2026-07-16 14:32:18',
  },
  {
    id: 'usage-20260716-140506',
    userName: 'i18n:pages.dataAccess.mock.user.orderOperationsService',
    userAccount: 'order-ops-service',
    targetType: 'database',
    targetName: 'i18n:pages.dataAccess.mock.target.orderAnalyticsDatabase',
    targetCode: 'order-ro.internal:5432',
    usedAt: '2026-07-16 14:05:06',
  },
  {
    id: 'usage-20260716-132451',
    userName: 'i18n:pages.dataAccess.mock.user.liNa',
    userAccount: 'li.na@example.com',
    targetType: 'endpoint',
    targetName: 'i18n:pages.dataAccess.mock.target.orderSearch',
    targetCode: 'order-search',
    usedAt: '2026-07-16 13:24:51',
  },
  {
    id: 'usage-20260716-115903',
    userName: 'i18n:pages.dataAccess.mock.user.customerServiceWorkspace',
    userAccount: 'customer-service-app',
    targetType: 'database',
    targetName: 'i18n:pages.dataAccess.mock.target.crmPrimaryDatabase',
    targetCode: 'crm-pg.internal:5432',
    usedAt: '2026-07-16 11:59:03',
  },
  {
    id: 'usage-20260716-104726',
    userName: 'i18n:pages.dataAccess.mock.user.wangQiang',
    userAccount: 'wang.qiang@example.com',
    targetType: 'endpoint',
    targetName: 'i18n:pages.dataAccess.mock.target.customerProfile',
    targetCode: 'customer-profile',
    usedAt: '2026-07-16 10:47:26',
  },
  {
    id: 'usage-20260715-181442',
    userName: 'i18n:pages.dataAccess.mock.user.analyticsService',
    userAccount: 'analytics-service',
    targetType: 'database',
    targetName: 'i18n:pages.dataAccess.mock.target.orderAnalyticsDatabase',
    targetCode: 'order-ro.internal:5432',
    usedAt: '2026-07-15 18:14:42',
  },
]
