import type { FieldPolicyRecord, UsageRecord } from './types'

export const initialPolicies: FieldPolicyRecord[] = [
  {
    id: 'policy-customer-service',
    name: '客服基础字段权限',
    endpointCode: 'customer-profile',
    subject: '角色：customer_service',
    allowedFields: ['customer_id', 'name', 'level', 'status'],
    deniedFields: ['mobile', 'id_card'],
    status: 'published',
    version: 5,
    updatedAt: '今天 10:02',
  },
  {
    id: 'policy-order-ops',
    name: '订单运营查询权限',
    endpointCode: 'order-search',
    subject: '角色：order_operator',
    allowedFields: ['order_id', 'amount', 'status', 'created_at'],
    deniedFields: ['buyer_mobile'],
    status: 'published',
    version: 2,
    updatedAt: '昨天 17:45',
  },
  {
    id: 'policy-partner-app',
    name: '合作方应用权限',
    endpointCode: 'partner-billing',
    subject: '服务账号：partner_app',
    allowedFields: ['bill_id', 'period', 'amount'],
    deniedFields: ['internal_cost'],
    status: 'draft',
    version: 1,
    updatedAt: '今天 08:40',
  },
]

export const initialUsageRecords: UsageRecord[] = [
  {
    id: 'usage-20260716-143218',
    userName: '张伟',
    userAccount: 'zhang.wei@example.com',
    targetType: 'endpoint',
    targetName: '客户档案查询',
    targetCode: 'customer-profile',
    usedAt: '2026-07-16 14:32:18',
  },
  {
    id: 'usage-20260716-140506',
    userName: '订单运营服务',
    userAccount: 'order-ops-service',
    targetType: 'database',
    targetName: '订单分析库',
    targetCode: 'order-ro.internal:5432',
    usedAt: '2026-07-16 14:05:06',
  },
  {
    id: 'usage-20260716-132451',
    userName: '李娜',
    userAccount: 'li.na@example.com',
    targetType: 'endpoint',
    targetName: '订单检索',
    targetCode: 'order-search',
    usedAt: '2026-07-16 13:24:51',
  },
  {
    id: 'usage-20260716-115903',
    userName: '客服工作台',
    userAccount: 'customer-service-app',
    targetType: 'database',
    targetName: 'CRM 主库',
    targetCode: 'crm-pg.internal:5432',
    usedAt: '2026-07-16 11:59:03',
  },
  {
    id: 'usage-20260716-104726',
    userName: '王强',
    userAccount: 'wang.qiang@example.com',
    targetType: 'endpoint',
    targetName: '客户档案查询',
    targetCode: 'customer-profile',
    usedAt: '2026-07-16 10:47:26',
  },
  {
    id: 'usage-20260715-181442',
    userName: '数据分析服务',
    userAccount: 'analytics-service',
    targetType: 'database',
    targetName: '订单分析库',
    targetCode: 'order-ro.internal:5432',
    usedAt: '2026-07-15 18:14:42',
  },
]
