export type Role = 'user' | 'assistant' | 'tool' | 'system'

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = 'message' | 'trace' | 'error'

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string
  name?: string
}

export type UIMediaKind = 'image' | 'video' | 'file'

export interface UIMediaAttachment {
  kind: UIMediaKind
  url?: string
  name?: string
}

export interface UIMessage {
  id: string
  role: Role
  content: string
  kind?: MessageKind
  isStreaming?: boolean
  createdAt: number
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[]
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[]
  /** Signed or local UI-renderable media attachments. */
  media?: UIMediaAttachment[]
  /** Optional answer choices for a pending ask_user question. */
  buttons?: string[][]
}

export interface ChatSummary {
  /** Server-side session key, e.g. ``websocket:abcd-...``. */
  key: string
  /** Local channel + chat_id parts derived from ``key`` for convenience. */
  channel: string
  chatId: string
  createdAt: string | null
  updatedAt: string | null
  title?: string
  preview: string
}
