import type { UIMediaAttachment } from '@/api/media'

export type Role = 'user' | 'assistant' | 'tool' | 'system'

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = 'message' | 'trace' | 'error'

export type ChatTaskStatus =
  | 'CREATED'
  | 'ANALYZING'
  | 'ROUTING'
  | 'CODING'
  | 'TESTING'
  | 'DEPLOYING'
  | 'COMPLETED'
  | 'PENDING_APPROVAL'
  | 'FAILED'

export interface ChatTaskError {
  stage: string
  message: string
}

export interface ChatTask {
  title: string
  status: ChatTaskStatus
  task_id: string
  tenant_id: string
  created_at: string
  updated_at: string
  last_error: ChatTaskError | null
  retry_count: number
  current_node: string
  web_url?: string | null
}

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string
  name?: string
}

export type {
  ChatSummary,
} from '@/api/chat'

export type {
  UIMediaAttachment,
  UIMediaKind,
} from '@/api/media'

export interface UIMessage {
  id: string
  role: Role
  content: string
  kind?: MessageKind
  isStreaming?: boolean
  createdAt: number
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[]
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[]
  /** Signed or local UI-renderable media attachments. */
  media?: UIMediaAttachment[]
  /** Optional answer choices for a pending ask_user question. */
  buttons?: string[][]
  /** Task-processing bubble payload, keyed by websocket bubble_id. */
  task?: ChatTask
}

export interface TaskConfirmationViewState {
  pendingTask:
    | {
        confirmation_id: string
        title: string
        task_type: 'process' | 'container' | 'direct_result'
        markdown: string
      }
    | null
  submitting: boolean
}
