.git
.gitignore
.DS_Store
._*
**/._*
.idea
.vscode
.turbo
.superpowers
.codex

node_modules
**/node_modules
.pnpm-store

dist
**/dist
dist-ssr
**/dist-ssr

logs
*.log
pnpm-debug.log*
npm-debug.log*
yarn-debug.log*
yarn-error.log*

*.local
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
